version: "3"

services:
  exist:
    image: existdb/existdb:release
    networks:
      - default
    volumes:
      - data:/exist/data

  redis:
    image: "redis:alpine"
    command: redis-server
    networks:
      - default
    volumes:
      - redis:/data

  proxy:
    build: .
    depends_on:
      - redis
      - exist
    networks:
      - default
    environment:
      - EXIST_URL_BASE=http://exist:8080/exist/apps/prodomo
      - REDIS_URL=redis://redis:6379
      - REDIS_EXPIRY_SEC=2628000 # 1 Month

networks:
  default:

volumes:
  data:
  redis:
